// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDliSzgsdhmmcfHzeLBQulrHA0PLloRSC8',
    appId: '1:899408578191:web:ce8cf97521a73bec2292fa',
    messagingSenderId: '899408578191',
    projectId: 'bilsem-kus-tanima',
    authDomain: 'bilsem-kus-tanima.firebaseapp.com',
    databaseURL: 'https://bilsem-kus-tanima-default-rtdb.firebaseio.com',
    storageBucket: 'bilsem-kus-tanima.firebasestorage.app',
    measurementId: 'G-4S3ZNL2DYY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9_A16GEOyBJ6jiZ-cU8vLKTeo4eOSMxg',
    appId: '1:899408578191:android:93d25234588ba1282292fa',
    messagingSenderId: '899408578191',
    projectId: 'bilsem-kus-tanima',
    databaseURL: 'https://bilsem-kus-tanima-default-rtdb.firebaseio.com',
    storageBucket: 'bilsem-kus-tanima.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjgStRhhzOpn0zRrpqKDPBdhLwrAXddVY',
    appId: '1:899408578191:ios:307aaea1552aa86c2292fa',
    messagingSenderId: '899408578191',
    projectId: 'bilsem-kus-tanima',
    databaseURL: 'https://bilsem-kus-tanima-default-rtdb.firebaseio.com',
    storageBucket: 'bilsem-kus-tanima.firebasestorage.app',
    iosBundleId: 'com.example.bilsemProje',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjgStRhhzOpn0zRrpqKDPBdhLwrAXddVY',
    appId: '1:899408578191:ios:307aaea1552aa86c2292fa',
    messagingSenderId: '899408578191',
    projectId: 'bilsem-kus-tanima',
    databaseURL: 'https://bilsem-kus-tanima-default-rtdb.firebaseio.com',
    storageBucket: 'bilsem-kus-tanima.firebasestorage.app',
    iosBundleId: 'com.example.bilsemProje',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDliSzgsdhmmcfHzeLBQulrHA0PLloRSC8',
    appId: '1:899408578191:web:bb69550a8a1765912292fa',
    messagingSenderId: '899408578191',
    projectId: 'bilsem-kus-tanima',
    authDomain: 'bilsem-kus-tanima.firebaseapp.com',
    databaseURL: 'https://bilsem-kus-tanima-default-rtdb.firebaseio.com',
    storageBucket: 'bilsem-kus-tanima.firebasestorage.app',
    measurementId: 'G-WTZYBVZJJN',
  );

}